### ISSUE TITLE
הערות/הארות על האפליקציה

### ISSUE THREAD

**Issue by sigalit1** [Koda-Project/babysitter#16]
היי :) כל מה שאני כותבת זה לפי איך שזה נראה אצלי במובייל ביחס לפרוטוטייפ שעבדתם לפיו
קודם כל, עבודה פצצה! סחטיין עליכם.
ועכשיו כמה דברים שצריך לתקן - תשימו לב, על מנת להבין טוב יותר את הגדלים של הכפתורים, האדר, האייקונים, השדות והצ'קבוקסים. תפתחו את זה אצלכם במובייל (את מה שעשיתם יחד עם הלינק המצורף https://bit.ly/2XVvWtu ), זה אמור להיות בגודל האצבע שלכם פחות או יותר. באזור 40PX גובה בשדות ובכפתורים ובהתאם גם השטח לחיצה של האייקונים. 

. **עמוד ראשי** 
1.- להגדיל בבקשה את הלוגואים לפחות פי 1.5
2. להוריד את "או להיכנס באמצעות חשבון גוגל
3. לעשות רווח בין הכפתור כניסה לכפתור כניסה עם גוגל ולרשום ביניהם -או- כמו בעיצוב
4. להוריד את הכפתור משתמש חדש למטה. לרשום מעליו " עוד לא  נרשמת? לחץ כאן"
* את כל הפתורים להקטין לרוחב 220 PX ולהגדיל ל 40 PX גובה.

**עמוד " תוצאות חיפוש"** 
1. להגדיל את הכפתורים של הוואטסאפ ושל הטלפון פי 1.5
2. להגדיל את "לפרטים נוספים" ב- 2 PX
3. למרכז את  כותרת "תוצאות החיפוש"
4. להגדיל את ההאדר (הסגול)
5. להגדיל את האייקון של ההמבורגר

**תפריט**
1. להגדיל את האייקונים כולם פי 1.5
**החשבון שלי**
1. לחיצה על עיר מגורים, אמורה לפתוח רשימה של עריםם חיפוש העיר - יש דוגמה בפרוטוטייפ
2. רמת תפקוד - לרשום הילד/ה
3. השדה לא שלם בבורדר שלו
4. את השעות בפרטי המשרה: להסיר "התחלה" ו "סיום" לעשות קו שיפריד בין השעות כאשר התחלה יהיה מצד שמאל וסיום מצד ימין
דוגמה: 12:00   - 8:00
5. את הכפתור " עדכן" לשנות ל "עדכון פרסום" לפי הפרוטוטיים. ולפי המידות והצבעים

**פרסום משרה זמנית** 
1. המידות של העמוד אינן תקינות, זה זולג החוצה מהמסך.
2. השדה של המספר ילדים אינו תקין. "מספר ילדים" אמור להיות בצד ימין (האפליקציה בעברית)
 3. הקלנדר אינו תקין - בסימון תאריך הוא יוצא בלי שניתן לעדכן את השעה.
4. לנוסת להפריד שהקלנדר יהיה כמו של אנדרואיד והשעה כמו שעתשים בפרטי שמרה - הוא יצא שם מהמם.

**שאלות ותשובות נפוצות**
1. הכתב ממש קטן - להגדיל בעוד 2 PX לפחות בשאלה עצמה ולא בתשובות
2. כל התוכן לא מתוח על כל המסך כמו בפרוטוטייפ
3. להגדיל את ה + ולמרכז אותו למלבן של השאלה
4. לעדכן בכל המלל במקום נקודה (.) בזכר נקבה, לשים לוכסן (/).
5. להגדיל את האייקונים של המייל והוואטסאפ ולרווח ביניהם. אם אפשר להוריד את ההילה הלבנה שיש מסביבם, מקסימום אשלח לכם אותם כ-SVG להטמעה

**תנאי שימוש**
1. הסרתי את המשפט הראשון, תסירו אותו גם בבקשה.
2. אותה הערה לגבי ההילה הלבנה של האייקונים

**כרטיס מתוצאות החיפוש**
יצא מהמם!!!
1. האייקונים אמורים להיות סטיקי לתחתית העמוד, גם בגלילה. ומתוחים לרוחב העמוד כמו בפרוטוטייפ.
2. הוספתי ספרות בכוכבים, תוסיפו גם בבקשה. 
3. להגדיל את הכפתור  ולכתוב "שליחה"
4. הרעיון של השליחת מייל - מטורף!!!! שיחקתם אותה

**הרשמה**
1. להוריד את הכל למטה לפחות ברבע מסך
2. להגדיל את הכפתור ל 40 PX
3. הגרפיקה חסרה באלמנטים. אם אתם צריכים אשלח לכם את זה ב SVG
4.למה צריך פה את "הכנס כתובת מייל"?
5. הכתובת מייל עולה על הלייבל

**הרשמה כבייביסיטר**
1. בטווח חיפוש כשמשנים את המספר נשאר שם נקודה צבועה על הקו.
2. בבחירת מועד - זה מרצד , שלחתי ללהב סרטון
3. לשנות את השעות כמו ההערה לעיל
4. אני מעדיף לעשות בייביסטר - ליישר את כל הגילאים לימין , למרכז את הריבועים למספרים  ולהגדיל את הריבועים פי 2 לפחות, ולרווח בין השורות. במובייל זה צריך להיות מספיק רחב ללחיצת אצבע
5. השדה מאוד צר, ולכן גם מה שנמצא בתוך(גילאים) מאוד מאוד קטן עם הX למחיקה. להגדיל הכל כמון בפרוטוטייפ. 
6. עיסוק נוכחי - הבורדר של השדה לא שלם 
7. את הכפתור לעשות כמו בעיצוב 
8. בבחירת העדפת מוגבלות זה מרצד
9.בעיר מגורים אותה הערה כמו לעיל - פתיחת דף חדש עם רשימת ערים יש לכם את הרשימה שלך הערים בנושיין.

**תנאי שימוש** אחרי ההרשמה
1. למרכז את "תנאי שימוש" להאדר הסגול
2. להסיר את המשפט הראשון
3. להגדיל את האייקונים 

נראה לי שזהו בנתיים. אם יש שאלות תוך כדי תציפו שנוכל לתקן תוך כדי.
עבודה טובה ! :) תודה רבה רבה

**Comment by noamschwartz** [comment]
Broken down into sub-problems
