### ISSUE TITLE
כרטיס מתוצאות החיפוש

### ISSUE THREAD

**Issue by noamschwartz** [Koda-Project/babysitter#24]
האייקונים אמורים להיות סטיקי לתחתית העמוד, גם בגלילה. ומתוחים לרוחב העמוד כמו בפרוטוטייפ.
הוספתי ספרות בכוכבים, תוסיפו גם בבקשה.
להגדיל את הכפתור ולכתוב "שליחה"
הרעיון של השליחת מייל - מטורף!!!! שיחקתם אותה

**Comment by noamschwartz** [comment]
Numbers in stars still missing

**Comment by Lahav1** [comment]
בתיאום עם סיגלית יורדים מהמספרים על הכוכבים
